{
 "title": "Container Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\"}, container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"$pod\"}, container_label_io_kubernetes_container_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage in Cores with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_name=~\"$pod\", \n            container_label_io_kubernetes_container_name=~\"$container\", \n            container_label_io_kubernetes_pod_namespace=~\"$namespace\", \n            image!=\"\", \n            container_label_io_cri_containerd_kind=\"container\"\n            }[1m]\n        )\n    ) \nby (\n    container_label_io_kubernetes_pod_name, \n    container_label_io_kubernetes_container_name\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits\n    {\n        exported_pod=~\"$pod\",\n        exported_namespace=~\"$namespace\", \n        exported_container=~\"$container\",\n        unit=\"core\"\n    })",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests\n    {\n        exported_pod=~\"$pod\",\n        exported_namespace=~\"$namespace\", \n        exported_container=~\"$container\",\n        unit=\"core\"\n    })",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory Usage in Bytes with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes\n{\n    container_label_io_kubernetes_pod_namespace=~\"$namespace\", \n    container_label_io_kubernetes_pod_name=~\"$pod\",\n    container_label_io_kubernetes_container_name=~\"$container\",\n    container_label_io_cri_containerd_kind=\"container\"\n}",
     "legendFormat": "{{ container_label_io_kubernetes_container_name }} in {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits\n{\n    exported_namespace=\"$namespace\", \n    exported_pod=~\"$pod\", \n    exported_container=~\"$container\", \n    unit=\"byte\"\n}",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests\n{\n    exported_namespace=\"$namespace\", \n    exported_pod=~\"$pod\", \n    exported_container=~\"$container\", \n    unit=\"byte\"\n})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(\n    container_network_receive_bytes_total\n    {\n        container_label_io_kubernetes_pod_namespace=~\"$namespace\", \n        container_label_io_kubernetes_pod_name=~\"$pod\"\n    }[1m]) * 8",
     "legendFormat": "Recive - {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "irate(\n    container_network_transmit_bytes_total\n    {\n        container_label_io_kubernetes_pod_namespace=~\"$namespace\", \n        container_label_io_kubernetes_pod_name=~\"$pod\"\n    }[1m]\n) * 8",
     "legendFormat": "Transmit - {{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  }
 ]
}