apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api-grpc
  labels:
    app: post-api-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-api-grpc
  template:
    metadata:
      labels:
        app: post-api-grpc
    spec:
      containers:
      - command:
        - ./api
        image: post-api-grpc:latest
        # for local development with "kind", otherwise set to IfNotPresent or Always (if using :latest)
        imagePullPolicy: Never
        name: post-api-grpc
        env:
        - name: POST_API_INTERVAL_MILLIS
          value: "500"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: info
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        ports:
        - containerPort: 8888
          protocol: TCP
