apiVersion: v1
kind: Service
metadata:
  name: post-api-grpc
  labels:
    app: post-api-grpc
spec:
  ports:
  - name: post-api-grpc-port
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: post-api-grpc
  type: ClusterIP
