apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-grpc
  labels:
    app: post-storage-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-storage-grpc
  template:
    metadata:
      labels:
        app: post-storage-grpc
    spec:
      containers:
      - command:
        - ./storage
        image: post-storage-grpc:latest 
        # for local development with "kind", otherwise set to IfNotPresent or Always (if using :latest)
        imagePullPolicy: Never 
        name: post-storage-grpc
        env:
        - name: POST_STORAGE_INTERVAL_MILLIS
          value: "50000"
        - name: POST_STORAGE_SLEEP_TIME_MILLIS
          value: "1500"
        ports:
        - containerPort: 8888
          protocol: TCP
