apiVersion: v1
kind: Service
metadata:
  name: post-storage-grpc
  labels:
    app: post-storage-grpc
spec:
  ports:
  - name: post-storage-grpc
    port: 8890
    protocol: TCP
    targetPort: 8890
  selector:
    app: post-storage-grpc
  type: ClusterIP
