version: "3.7"
services:
  post_api:
    build: .
    image: post-api-http:latest
    container_name: post-api-http
    ports:
      - 8080:8080/tcp
    restart: always
    networks:
      - http-net 

  post_storage:
    build: ./post_storage
    image: post-storage-http:latest
    container_name: post-storage-http
    ports:
      - 8090:8090/tcp
    restart: always
    networks:
      - http-net

networks:
  http-net:
    name: http-net
    driver: bridge