// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: post_api.proto

package post_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShowPostRequest) Reset() {
	*x = ShowPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPostRequest) ProtoMessage() {}

func (x *ShowPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPostRequest.ProtoReflect.Descriptor instead.
func (*ShowPostRequest) Descriptor() ([]byte, []int) {
	return file_post_api_proto_rawDescGZIP(), []int{0}
}

func (x *ShowPostRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ShowPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ShowPostResponse) Reset() {
	*x = ShowPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPostResponse) ProtoMessage() {}

func (x *ShowPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPostResponse.ProtoReflect.Descriptor instead.
func (*ShowPostResponse) Descriptor() ([]byte, []int) {
	return file_post_api_proto_rawDescGZIP(), []int{1}
}

func (x *ShowPostResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShowPostResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_post_api_proto protoreflect.FileDescriptor

var file_post_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x27, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x10, 0x53, 0x68, 0x6f,
	0x77, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x3a, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x50, 0x49,
	0x12, 0x2f, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x53,
	0x68, 0x6f, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_post_api_proto_rawDescOnce sync.Once
	file_post_api_proto_rawDescData = file_post_api_proto_rawDesc
)

func file_post_api_proto_rawDescGZIP() []byte {
	file_post_api_proto_rawDescOnce.Do(func() {
		file_post_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_post_api_proto_rawDescData)
	})
	return file_post_api_proto_rawDescData
}

var file_post_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_post_api_proto_goTypes = []interface{}{
	(*ShowPostRequest)(nil),  // 0: ShowPostRequest
	(*ShowPostResponse)(nil), // 1: ShowPostResponse
}
var file_post_api_proto_depIdxs = []int32{
	0, // 0: PostAPI.ShowPost:input_type -> ShowPostRequest
	1, // 1: PostAPI.ShowPost:output_type -> ShowPostResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_post_api_proto_init() }
func file_post_api_proto_init() {
	if File_post_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_post_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_post_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_api_proto_goTypes,
		DependencyIndexes: file_post_api_proto_depIdxs,
		MessageInfos:      file_post_api_proto_msgTypes,
	}.Build()
	File_post_api_proto = out.File
	file_post_api_proto_rawDesc = nil
	file_post_api_proto_goTypes = nil
	file_post_api_proto_depIdxs = nil
}
