apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-http
  labels:
    app: post-storage-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-storage-http
  template:
    metadata:
      labels:
        app: post-storage-http
    spec:
      containers:
      - command:
        - ./storage
        image: post-storage-http:latest
        imagePullPolicy: Never
        name: post-storage-http
        env:
        - name: POST_STORAGE_INTERVAL_MILLIS
          value: "50000"
        - name: POST_STORAGE_SLEEP_TIME_MILLIS
          value: "1500"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: info
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: 99
        ports:
        - containerPort: 8080
          protocol: TCP
