apiVersion: v1
kind: Service
metadata:
  name: post-storage-http
  labels:
    app: post-storage-http
spec:
  ports:
  - name: post-storage-http-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: post-storage-http
  type: ClusterIP