apiVersion: v1
kind: Service
metadata:
  name: post-storage-http
  labels:
    app: post-storage-http
spec:
  ports:
  - name: post-storage-http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: post-storage-http
  type: ClusterIP